language: ruby
dist: xenial
os: linux
cache:
  directories:
    - vendor/bundle
# Source: <https://docs.travis-ci.com/user/languages/ruby/#bundler-20>
before_install:
  - gem update --system '3.1.2' --no-document
  - gem uninstall -v '< 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-document
  - nvm use v11.0.0
  - bundle config set path vendor/bundle
install: "bundle install --jobs=3 --retry=3"
script: "bundle exec rake"
rvm:
  - 2.4.9
  - 2.5.8
  - 2.6.6
  - 2.7.1
gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_4_2.gemfile
